#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: make
# autospec version: v10
# autospec commit: 5905be9
#
Name     : ninja
Version  : 1.12.1
Release  : 27
URL      : https://github.com/ninja-build/ninja/archive/v1.12.1/ninja-1.12.1.tar.gz
Source0  : https://github.com/ninja-build/ninja/archive/v1.12.1/ninja-1.12.1.tar.gz
Summary  : Ninja is a small build system with a focus on speed.
Group    : Development/Tools
License  : Apache-2.0
Requires: ninja-bin = %{version}-%{release}
Requires: ninja-license = %{version}-%{release}
Requires: ninja-python = %{version}-%{release}
Requires: ninja-python3 = %{version}-%{release}
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
Ninja is yet another build system. It takes as input the interdependencies of files (typically source code and output executables) and
orchestrates building them, quickly.

Ninja joins a sea of other build systems. Its distinguishing goal is to be fast. It is born from my work on the Chromium browser project,
which has over 30,000 source files and whose other build systems (including one built from custom non-recursive Makefiles) can take ten
seconds to start building after changing one file. Ninja is under a second.

%package bin
Summary: bin components for the ninja package.
Group: Binaries
Requires: ninja-license = %{version}-%{release}

%description bin
bin components for the ninja package.


%package license
Summary: license components for the ninja package.
Group: Default

%description license
license components for the ninja package.


%package python
Summary: python components for the ninja package.
Group: Default
Requires: ninja-python3 = %{version}-%{release}

%description python
python components for the ninja package.


%package python3
Summary: python3 components for the ninja package.
Group: Default
Requires: python3-core
Requires: ninja
Provides: pypi(ninja)

%description python3
python3 components for the ninja package.


%prep
%setup -q -n ninja-1.12.1
cd %{_builddir}/ninja-1.12.1
pushd ..
cp -a ninja-1.12.1 buildavx2
popd

%build
## build_prepend content
python3 configure.py --bootstrap --verbose
## build_prepend end
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1715874036
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
make  %{?_smp_mflags}  ||:

pushd ../buildavx2
## build_prepend content
python3 configure.py --bootstrap --verbose
## build_prepend end
GOAMD64=v3
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS -march=x86-64-v3 "
make  %{?_smp_mflags}  ||:
popd

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1715874036
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/ninja
cp %{_builddir}/ninja-%{version}/COPYING %{buildroot}/usr/share/package-licenses/ninja/b7a11257fc8046a2f00f1a685da1f2bca2a3ba50 || :
export GOAMD64=v2
GOAMD64=v3
pushd ../buildavx2/
%make_install_v3 ||:
popd
GOAMD64=v2
%make_install ||:
## install_append content
install -Dpm0755 ninja -t %{buildroot}/usr/bin/

_PYTHON_VER=$(python3 -c 'import sysconfig; print(sysconfig.get_python_version())')
_PYTHON_PLATLIB=$(python3 -c 'import sysconfig; print(sysconfig.get_path("platlib"))')
mkdir -p %{buildroot}"${_PYTHON_PLATLIB}"/ninja
mkdir -p %{buildroot}"${_PYTHON_PLATLIB}"/ninja-%{version}-py"${_PYTHON_VER}".egg-info
touch %{buildroot}"${_PYTHON_PLATLIB}"/ninja/__init__.py
printf "Name: ninja\nVersion: %{version}\n" > %{buildroot}"${_PYTHON_PLATLIB}"/ninja-%{version}-py"${_PYTHON_VER}".egg-info/PKG-INFO
## install_append end
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/ninja

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/ninja/b7a11257fc8046a2f00f1a685da1f2bca2a3ba50

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
